version: "3.8"

services:
  database:
    image: postgres:13
    container_name: postgres-db
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password

    secrets:
      - db_password

    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

    ports:
      - "5432:5432"

    networks:
      - backend-network

  backend:
    build: ./-pwc-Full-Stack-Application-using-React-JS-Nodejs-PostgreSQL/student-server
    container_name: backend
    restart: always

    depends_on:
      - database

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

    secrets:
      - db_password

    ports:
      - "3005:3005"

    networks:
      - backend-network
      - frontend-network

  webapp:
    build:
      context: ./-pwc-Full-Stack-Application-using-React-JS-Nodejs-PostgreSQL/student-web
      args:
        VITE_BACKEND_BASE_URL: ${VITE_BACKEND_BASE_URL}
    restart: always

    depends_on:
      - backend

    ports:
      - "5173:5173"

    networks:
      - frontend-network

volumes:
  db_data:

networks:
  backend-network:
  frontend-network:

secrets:
  db_password:
    file: ${POSTGRES_PASSWORD_FILE}
